apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-cache
  name: go-cache
  namespace: test-mazerunners
spec:
  ports:
    - name: go-cache-port
      port: 80
      nodePort: 1337
      protocol: TCP
      targetPort: 1337
  selector:
    app: go-cache # selecting the pod
    name: go-cache
  type: NodePort
